### ISSUE TITLE
Relative inputfilenames mess up with outputfilename

### ISSUE THREAD

**Issue by nukeador** [mozilla/sumo-mt#3]
If you provide as input filename a relative path such as

../export/my-file.txt

This condition messes with the dots and creates wrong output filenames

https://github.com/mozilla/sumo-mt/blob/master/WikiParser.py#L57

**Comment by soccerjustinh1** [comment]
This is related to the issue #2 (https://github.com/mozilla/sumo-mt/issues/3) when the directory name is a relative instead of an absolute path. This causes the incorrect output names to be created. I have tested the pull request (https://github.com/mozilla/sumo-mt/pull/5) and this fix also solves the problem identified in this issue related to relative paths.

**Comment by nukeador** [comment]
Thanks!
